name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        PYTHONPATH=. pytest

  security-scan:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t fib-api:latest .

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'fib-api:latest'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

  smoke-test:
    runs-on: ubuntu-latest
    needs: security-scan

    steps:
    - uses: actions/checkout@v3

    - name: Run Docker Compose
      run: docker-compose up -d --build

    - name: Wait for services to be healthy
      run: sleep 10 # A simple wait, in a real scenario you'd use a health check

    - name: Run smoke test
      run: |
        response=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:8000/v1/fib?n=10")
        if [ "$response" -ne 200 ]; then
          echo "Smoke test failed with status code $response"
          exit 1
        fi
        echo "Smoke test passed!"

    - name: Tear down services
      run: docker-compose down 