name: Release Workflow

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-and-smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run unit tests
        run: PYTHONPATH=. pytest

      - name: Build Docker image
        run: docker build --no-cache -t fib-api:latest .
      
      - name: Install and verify docker-compose
        run: |
          pip install docker-compose
          which docker-compose

      - name: Run Smoke Test with Docker Compose
        run: |
          docker-compose up -d --build
          sleep 15
          curl -f "http://localhost:8000/v1/fib?n=10"
          docker-compose down 